### ISSUE TITLE
Supervisor behaviour

### ISSUE THREAD

**Issue by deblauwetom** [troglobit/watchdogd#13]
Hello!

Thanks for this software it seems very well done!

I just have a question about the supervisor script. I am working in the pi3 B+ and I want to prevent the system from rebooting when I am remote debugging. So I want to have a system where I put the empty file called "noreboot" in my home folder of the device, and then when I get a "deadline" cause for my app, the watchdog should do nothing. So I have a supervisor shell script where I can check all these things. But my question is: to perform the reboot, what is the preferred way so I get the reset causes correct. Right now, when I issue "watchdogctl -c $2 fail 1 $4" in this supervisor script, I get into an infinite loop... So using "watchdogctl reset 1 $4" works, but then I can't log the correct reboot reason I think? So how should I do that?

Best regards,
Tom,

**Comment by troglobit** [comment]
Hi, sorry for the late reply!

For your use-case you should use `watchdogctl -c $2 fail $4`.  If that doesn't work we have a bug.  I'll have to look into that in more detail.

**Comment by troglobit** [comment]
Ah, now I see ... my bad, `watchdogctl fail` should not be called from the script, that will indeed create an infinite loop.  I'll have to document this.

Instead, return non-zero from your script and the supervisor will save the cause and trigger a reset.

**Comment by deblauwetom** [comment]
alright thanks I shall test this soon.

**Comment by deblauwetom** [comment]
I tested this and it indeed works ok now.

**Comment by troglobit** [comment]
Awesome, thank you for following up! :+1:
