### ISSUE TITLE
Failed connecting to wdog: Operation not supported

### ISSUE THREAD

**Issue by BenjaminLeconte** [troglobit/watchdogd#19]
Hi,

I try to use watchdogd to monitor some services.
I made a build of watchdogd to run on a arm processor.
The service looks running well but the sample application looks not able to connect to the watchdogd service.

I tried the ex1 sample, and this code : 

```
	id = wdog_subscribe(NULL, 3000, &ack);
	DEBUG("id is %d", id);

	if (id < 0) {
		perror("Failed connecting to wdog");
		return 1;
	}
```

Is failing, it is returning an error "Failed connecting to wdog: Operation not supported"
I have added a debug line to see the id value returned, and the value is '-95'

Do you have an idea how to debug this issue?
Thanks and regards,

**Comment by BenjaminLeconte** [comment]
Issue found, i just needed to set up a configuration for the supervisor in the config file /etc/watchdogd.conf 
By default, the supervisor is disabled, this explain the not supported error

Closing the issue.

**Comment by troglobit** [comment]
Happy to hear you using watchdogd, also glad you found the root cause to your problem. 

Please let me know if there is anything we can improve in the documentation.
