### ISSUE TITLE
error: conflicting types for ‘UNUSED’

### ISSUE THREAD

**Issue by MYasin93** [troglobit/watchdogd#2]
release version : watchdogd v3.0-beta1
platform : armv7l
---------------------------------------------------
I get that error message a lot when run make, That is the full output I got : 

> watchdogd.c:224:1: warning: parameter names (without types) in function declaration
 void exit_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
watchdogd.c:224:1: warning: parameter names (without types) in function declaration
watchdogd.c:224:47: error: conflicting types for ‘UNUSED’
 void exit_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                               ^
watchdogd.c:224:30: note: previous definition of ‘UNUSED’ was here
 void exit_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                              ^
watchdogd.c:339:1: warning: parameter names (without types) in function declaration
 static void reboot_timeout_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
watchdogd.c:339:1: warning: parameter names (without types) in function declaration
watchdogd.c:339:64: error: conflicting types for ‘UNUSED’
 static void reboot_timeout_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                                ^
watchdogd.c:339:47: note: previous definition of ‘UNUSED’ was here
 static void reboot_timeout_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                               ^
watchdogd.c: In function ‘wdt_reboot’:
watchdogd.c:363:48: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
   return uev_timer_init(ctx, &timeout_watcher, reboot_timeout_cb, NULL, timeout, 0);
                                                ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
watchdogd.c: At top level:
watchdogd.c:379:1: warning: parameter names (without types) in function declaration
 void reboot_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
watchdogd.c:379:1: warning: parameter names (without types) in function declaration
watchdogd.c:379:49: error: conflicting types for ‘UNUSED’
 void reboot_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                 ^
watchdogd.c:379:32: note: previous definition of ‘UNUSED’ was here
 void reboot_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                ^
watchdogd.c: In function ‘setup_signals’:
watchdogd.c:387:41: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigterm_watcher, exit_cb, NULL, SIGTERM);
                                         ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c:388:41: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigint_watcher,  exit_cb, NULL, SIGINT);
                                         ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c:389:41: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigquit_watcher, exit_cb, NULL, SIGQUIT);
                                         ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c:392:40: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigpwr_watcher, reboot_cb, NULL, SIGPWR);
                                        ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c: At top level:
watchdogd.c:448:1: warning: parameter names (without types) in function declaration
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
 ^
watchdogd.c:448:1: warning: parameter names (without types) in function declaration
watchdogd.c:448:47: error: conflicting types for ‘UNUSED’
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                                               ^
watchdogd.c:448:30: note: previous definition of ‘UNUSED’ was here
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                              ^
watchdogd.c:448:1: warning: parameter names (without types) in function declaration
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
 ^
watchdogd.c:448:64: error: conflicting types for ‘UNUSED’
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                                                                ^
watchdogd.c:448:47: note: previous definition of ‘UNUSED’ was here
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                                               ^
watchdogd.c: In function ‘main’:
watchdogd.c:683:40: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_timer_init(&ctx, &period_watcher, period_cb, NULL, T, T);
                                        ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t * (*)(), void * (*)(), int (*)()) {aka void (*)(struct uev * (*)(), void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
filenr.c:29:1: warning: parameter names (without types) in function declaration
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
filenr.c:29:1: warning: parameter names (without types) in function declaration
filenr.c:29:49: error: conflicting types for ‘UNUSED’
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                 ^
filenr.c:29:32: note: previous definition of ‘UNUSED’ was here
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                ^
filenr.c: In function ‘filenr_init’:
filenr.c:80:39: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  return uev_timer_init(ctx, &watcher, cb, NULL, T, T);
                                       ^
In file included from wdt.h:42:0,
                 from plugin.h:21,
                 from filenr.c:18:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
loadavg.c:38:1: warning: parameter names (without types) in function declaration
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
loadavg.c:38:1: warning: parameter names (without types) in function declaration
loadavg.c:38:49: error: conflicting types for ‘UNUSED’
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                 ^
loadavg.c:38:32: note: previous definition of ‘UNUSED’ was here
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                ^
loadavg.c: In function ‘loadavg_init’:
loadavg.c:85:39: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  return uev_timer_init(ctx, &watcher, cb, NULL, T, T);
                                       ^
In file included from wdt.h:42:0,
                 from plugin.h:21,
                 from loadavg.c:19:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
meminfo.c:45:1: warning: parameter names (without types) in function declaration
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
meminfo.c:45:1: warning: parameter names (without types) in function declaration
meminfo.c:45:49: error: conflicting types for ‘UNUSED’
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                 ^
meminfo.c:45:32: note: previous definition of ‘UNUSED’ was here
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                ^
meminfo.c: In function ‘meminfo_init’:
meminfo.c:128:39: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  return uev_timer_init(ctx, &watcher, cb, NULL, T, T);
                                       ^
In file included from wdt.h:42:0,
                 from plugin.h:21,
                 from meminfo.c:18:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
pmon.c:177:1: warning: parameter names (without types) in function declaration
 static void timeout(uev_t *w, void *arg, int UNUSED(events))
 ^
pmon.c:192:1: warning: parameter names (without types) in function declaration
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
pmon.c:192:1: warning: parameter names (without types) in function declaration
pmon.c:192:49: error: conflicting types for ‘UNUSED’
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                 ^
pmon.c:192:32: note: previous definition of ‘UNUSED’ was here
 static void cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                ^
pmon.c: In function ‘cb’:
pmon.c:228:40: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
    uev_timer_init(w->ctx, &p->watcher, timeout, p, p->timeout + 500, p->timeout + 500);
                                        ^
In file included from wdt.h:42:0,
                 from plugin.h:21,
                 from pmon.c:22:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void *, int (*)()) {aka void (*)(struct uev *, void *, int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
pmon.c: At top level:
pmon.c:361:1: warning: parameter names (without types) in function declaration
 int pmon_init(uev_ctx_t *ctx, int UNUSED(T))
 ^
pmon.c:361:5: error: conflicting types for ‘pmon_init’
 int pmon_init(uev_ctx_t *ctx, int UNUSED(T))
     ^
In file included from plugin.h:25:0,
                 from pmon.c:22:
pmon.h:21:5: note: previous declaration of ‘pmon_init’ was here
 int pmon_init   (uev_ctx_t *ctx, int T);
     ^
pmon.c: In function ‘pmon_init’:
pmon.c:389:36: warning: passing argument 3 of ‘uev_io_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  return uev_io_init(ctx, &watcher, cb, NULL, sd, UEV_READ);
                                    ^
In file included from wdt.h:42:0,
                 from plugin.h:21,
                 from pmon.c:22:
/usr/local/include/uev/uev.h:82:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_io_init        (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int fd, int events);
     ^
pmon.c: At top level:
pmon.c:392:1: warning: parameter names (without types) in function declaration
 int pmon_exit(uev_ctx_t *UNUSED(ctx))
 ^
pmon.c:392:5: error: conflicting types for ‘pmon_exit’
 int pmon_exit(uev_ctx_t *UNUSED(ctx))
     ^
In file included from plugin.h:25:0,
                 from pmon.c:22:
pmon.h:22:5: note: previous declaration of ‘pmon_exit’ was here
 int pmon_exit   (uev_ctx_t *ctx);
     ^
watchdogd.c:224:1: warning: parameter names (without types) in function declaration
 void exit_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
watchdogd.c:224:1: warning: parameter names (without types) in function declaration
watchdogd.c:224:47: error: conflicting types for ‘UNUSED’
 void exit_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                               ^
watchdogd.c:224:30: note: previous definition of ‘UNUSED’ was here
 void exit_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                              ^
watchdogd.c:339:1: warning: parameter names (without types) in function declaration
 static void reboot_timeout_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
watchdogd.c:339:1: warning: parameter names (without types) in function declaration
watchdogd.c:339:64: error: conflicting types for ‘UNUSED’
 static void reboot_timeout_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                                ^
watchdogd.c:339:47: note: previous definition of ‘UNUSED’ was here
 static void reboot_timeout_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                               ^
watchdogd.c: In function ‘wdt_reboot’:
watchdogd.c:363:48: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
   return uev_timer_init(ctx, &timeout_watcher, reboot_timeout_cb, NULL, timeout, 0);
                                                ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);
     ^
watchdogd.c: At top level:
watchdogd.c:379:1: warning: parameter names (without types) in function declaration
 void reboot_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
 ^
watchdogd.c:379:1: warning: parameter names (without types) in function declaration
watchdogd.c:379:49: error: conflicting types for ‘UNUSED’
 void reboot_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                                 ^
watchdogd.c:379:32: note: previous definition of ‘UNUSED’ was here
 void reboot_cb(uev_t *w, void *UNUSED(arg), int UNUSED(events))
                                ^
watchdogd.c: In function ‘setup_signals’:
watchdogd.c:387:41: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigterm_watcher, exit_cb, NULL, SIGTERM);
                                         ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c:388:41: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigint_watcher,  exit_cb, NULL, SIGINT);
                                         ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c:389:41: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigquit_watcher, exit_cb, NULL, SIGQUIT);
                                         ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c:392:40: warning: passing argument 3 of ‘uev_signal_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_signal_init(ctx, &sigpwr_watcher, reboot_cb, NULL, SIGPWR);
                                        ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:97:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t *, void * (*)(), int (*)()) {aka void (*)(struct uev *, void * (*)(), int (*)())}’
 int uev_signal_init    (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int signo);
     ^
watchdogd.c: At top level:
watchdogd.c:448:1: warning: parameter names (without types) in function declaration
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
 ^
watchdogd.c:448:1: warning: parameter names (without types) in function declaration
watchdogd.c:448:47: error: conflicting types for ‘UNUSED’
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                                               ^
watchdogd.c:448:30: note: previous definition of ‘UNUSED’ was here
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                              ^
watchdogd.c:448:1: warning: parameter names (without types) in function declaration
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
 ^
watchdogd.c:448:64: error: conflicting types for ‘UNUSED’
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                                                                ^
watchdogd.c:448:47: note: previous definition of ‘UNUSED’ was here
 static void period_cb(uev_t *UNUSED(w), void *UNUSED(arg), int UNUSED(event))
                                               ^
watchdogd.c: In function ‘main’:
watchdogd.c:683:40: warning: passing argument 3 of ‘uev_timer_init’ from incompatible pointer type [-Wincompatible-pointer-types]
  uev_timer_init(&ctx, &period_watcher, period_cb, NULL, T, T);
                                        ^
In file included from wdt.h:42:0,
                 from watchdogd.c:20:
/usr/local/include/uev/uev.h:87:5: note: expected ‘void (*)(uev_t *, void *, int) {aka void (*)(struct uev *, void *, int)}’ but argument is of type ‘void (*)(uev_t * (*)(), void * (*)(), int (*)()) {aka void (*)(struct uev * (*)(), void * (*)(), int (*)())}’
 int uev_timer_init     (uev_ctx_t *ctx, uev_t *w, uev_cb_t *cb, void *arg, int timeout, int period);

**Comment by troglobit** [comment]
Fixed on master branch, commit 00a71670e.  The GA release of v3.0 is just around the corner, but for the time being I suggest backporting that commit.

**Comment by troglobit** [comment]
Fixed in https://github.com/troglobit/watchdogd/releases/tag/3.0, just released!
