### ISSUE TITLE
Is there "libwdog-dev_3.0-1_amd64.deb" but for ARM ?

### ISSUE THREAD

**Issue by 123AWS7** [troglobit/watchdogd#3]

**Comment by troglobit** [comment]
Nope.

I have long-term plan to publish `.deb` files at http://deb.troglobit.com, but that repo-project is still some months off. And when it eventually goes live it'll initially focus on x86 (amd64).

**Comment by troglobit** [comment]
Let's face it, I'll never be able to support (cross-compiled) readily built binaries from this project.  It's just not my priority, so I'll just have to defer this to downstream projects like Debian and OpenWRT.

Closing.
