### ISSUE TITLE
Buildroot Package Config files?

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/watchdogd#31]
Are there any example Buildroot package config files for this package anywhere?

**Comment by hongkongkiwi** [comment]
Ahh somehow I must have missed your [official contribution in Oct](https://github.com/buildroot/buildroot/tree/master/package/watchdogd) (perhaps I'm using an older buildroot).

**Comment by troglobit** [comment]
Yup it's already in mainline Buildroot ☺️

**Comment by hongkongkiwi** [comment]
I had to make these changes to get it to work for me to use your latest commits (I'm storing some packages in external rather than the default package dir). This is a common mistake by directly referencing package/ but buildrootroot has a variable to use for the "real" package dir which is <PKGNAME>_PKGDIR.

Also WATCHDOGD_AUTORECONF = YES needed to be set otherwise it wouldn't generate the configure files. This is when pulling the files from git repo rather than your release so probably that's not needed in the mainline version.

```
18d14
< WATCHDOGD_AUTORECONF = YES
51c47
< 	$(INSTALL) -D -m 0755 ${WATCHDOGD_PKGDIR}/S01watchdogd \
---
> 	$(INSTALL) -D -m 0755 package/watchdogd/S01watchdogd \
```

**Comment by troglobit** [comment]
> I had to make these changes to get it to work for me to use your latest commits (I'm storing some packages in external rather than the default package dir). This is a common mistake by directly referencing package/ but buildrootroot has a variable to use for the "real" package dir which is _PKGDIR.

Ah, thanks!  I see now there are more packages that have the same mistake.  I'll make sure to fix this in upstream buildroot as soon as I find the time. 

I have three-four different projects that use BR2_EXTERNAL, are you saying it's possible to override the Buildroot packaged version of a program somehow, without setting up a `foo2`?

> Also WATCHDOGD_AUTORECONF = YES needed to be set otherwise it wouldn't generate the configure files. This is when pulling the files from git repo rather than your release so probably that's not needed in the mainline version.

Yeah, I prefer people use the released versions of my software, it's really hard to support otherwise, so I steer clear of foo_autoreconf=yes on released sw. You can add that to your local.mk easily anyway.

**Comment by hongkongkiwi** [comment]
**EDIT: I misread what you said and thought you were asking about the version of the package let me answer your actual question in another comment, but I left this because you might find it useful.**

I didn't paste those lines as I think this is not useful for mainline packages. From my understanding they want each build of buildroot to be a fixed point in time exactly with things hardcoded.

But for development or fast testing it's a pain, so I use this technique on my packages (like I'm doing with finit).

```
# finit.mk
FINIT_VERSION = $(patsubst "%",%,$(BR2_PACKAGE_FINIT_GIT_VERSION))
FINIT_SITE = $(patsubst "%",%,$(BR2_PACKAGE_FINIT_GIT_URL))
FINIT_SITE_METHOD = git
```

```
# Config.in
if BR2_PACKAGE_FINIT

config BR2_PACKAGE_FINIT_GIT_URL
  string "git repo"
  default "https://github.com/troglobit/finit.git"
  depends on BR2_PACKAGE_FINIT
  help
    git repo to clone from

config BR2_PACKAGE_FINIT_GIT_VERSION
  string "git version"
  default "4.3"
  depends on BR2_PACKAGE_FINIT
  help
    git tag, commit hash or branch to use for this package
```

This allows me to simply update the version (either a tag, branch or commit id) using the buildroot menu which is nice. For this to be less annoying I removed the hash check on the downloaded file (otherwise it would always be wrong).

**Comment by hongkongkiwi** [comment]
So, how do I override a package that's included without renaming it? ;)

I use a simple which searches my external/package dir and if it finds a dir there, it removes the corresponding directory in the buildroot/package dir. Since my builds are in a docker this change is only temporary (although I suppose it wouldn't really matter).

So I often will use this to copy the original package files and change the version if I need a special version (I have done this for a few packages including mosquitto). It makes it so easy to just pop a package in my external and if I decide to go back later then it works as well (I just remove from external).

```
#!/bin/bash

export BR2_EXTERNAL_DIR=${BR2_EXTERNAL_DIR:-"/external"}

[ -z "$BR2_EXTERNAL_DIR" ] && { echo >&2 "BR2_EXTERNAL_DIR not set!"; exit 1; }
[ -z "$BUILDROOT_DIR" ] && { echo >&2 "BUILDROOT_DIR not set!"; exit 1; }
[ -z "$BR2_DL_DIR" ] && { echo >&2 "BR2_DL_DIR not set!"; exit 1; }

cd "$BR2_EXTERNAL_DIR/package"

find *  -maxdepth 1 -type f -name "*.mk" -exec basename "{}" ".mk" \; | while IFS= read -r PACKAGE_NAME; do
  [ -d "${BUILDROOT_DIR}/package/${PACKAGE_NAME}" ] || continue
  echo "Removing package $PACKAGE_NAME from main buildroot dir"
  sed -i 's|^[ \t]*source "'${BR2_EXTERNAL_DIR}'/package/'${PACKAGE_NAME}'/Config\.in\.host"|\t#source "'${BR2_EXTERNAL_DIR}'/package/'${PACKAGE_NAME}'/Config.in.host"|' "${BUILDROOT_DIR}/package/Config.in.host"
  sed -i 's|^[ \t]*source "'${BR2_EXTERNAL_DIR}'/package/'${PACKAGE_NAME}'/Config\.in"|\t#source "'${BR2_EXTERNAL_DIR}'/package/'${BUILDROOT_DIR}'/Config\.in"|' "${BUILDROOT_DIR}/package/Config.in"
  sed -i 's|^[ \t]*source "package/'${PACKAGE_NAME}'/Config\.in\.host"|\t#source "package/'${PACKAGE_NAME}'/Config.in.host"|' "${BUILDROOT_DIR}/package/Config.in.host"
  sed -i 's|^[ \t]*source "package/'${PACKAGE_NAME}'/Config\.in"|\t#source "package/'${PACKAGE_NAME}'/Config\.in"|' "${BUILDROOT_DIR}/package/Config.in"
  [ -d "${BR2_DL_DIR}/${PACKAGE_NAME}" ] && rm -Rf "${BR2_DL_DIR}/${PACKAGE_NAME}"
  [ -d "${BUILDROOT_DIR}/package/${PACKAGE_NAME}" ] && rm -Rf "${BUILDROOT_DIR}/package/${PACKAGE_NAME}"
done
```

**Comment by hongkongkiwi** [comment]
The only update I'd make to the above script is just to first check if the package is included in the external Config.in or Config.host.in first THEN check the actual config file being used before doing anything. That way you can keep the dirs around even if your not actively using the package.

**Comment by troglobit** [comment]
I suspected you needed something like this.  At first I thought you had found an official way to do this, but the trick with building in a docker + the script can come in handy later on.  Thanks! :-)

**Comment by hongkongkiwi** [comment]
It's a real shame that Buildroot doesn't simply check the external directory first and then ignore any packages with the same name in the buildroot dir, to me that would be most logical. Clearly the user wants to override in this case.

I definitely highly recommend building uboot in a docker because then instead of having to build host packages for everything you want to use to manipulate the image during or after creation (which was a great idea before docker came long) now you can just ensure your docker images has all the tools you need. It's less work when doing a fresh rebuild and you can still lock the docker to the exact versions you need for a reproducible build.
