### ISSUE TITLE
add date when the reset occurred in the state file

### ISSUE THREAD

**Issue by doditaly** [troglobit/watchdogd#5]
Before system reset, watchdogd creates the watchdogd.state file with info about the reset cause. It could be very useful to write also the date/time when the reset occurred.

**Comment by troglobit** [comment]
On systems with correct time (many embedded systems don't have a battery backed RTC and no network connection to an NTP server, but) this could of course be read from the file system, the mtime value.

But sure, we could encode it in the file as well. What time format should we use? ;-)

**Comment by doditaly** [comment]
This is the changes I've done for my Linux embedded system in wdt.c file:

```
#include <time.h>
...
int wdt_fstore_reason(FILE *fp, wdog_reason_t *r, pid_t pid)
{
	time_t current_time;
    char* c_time_string;

	current_time = time(NULL);
	if (current_time != ((time_t)-1))
	{
		/* Convert to local time format. */
		c_time_string = ctime(&current_time);
		if (c_time_string != NULL)
			fprintf(fp, WDT_DATE_STR ": %s", c_time_string);
    }
    
	fprintf(fp, WDT_REASON_CNT ": %u\n", r->counter);
	fprintf(fp, WDT_REASON_PID ": %d\n", pid);
	fprintf(fp, WDT_REASON_WID ": %d\n", r->wid);
	fprintf(fp, WDT_REASON_LBL ": %s\n", r->label);
	fprintf(fp, WDT_REASON_CSE ": %d\n", r->cause);
	fprintf(fp, WDT_REASON_STR ": %s\n", wdog_reset_reason_str(r));

	return fclose(fp);
}
```

**Comment by doditaly** [comment]
alternatively the uptime is good

**Comment by troglobit** [comment]
Using `ctime()` is one format, I'd prefer ISO 8601 date-time format, e.g. 

    2011-08-12T20:17:46.384Z

How do you feel about that?  We also need to add support to read this on boot, since the state file is overwritten at boot.

**Comment by doditaly** [comment]
Ok
