### ISSUE TITLE
supervisor label size is not enough

### ISSUE THREAD

**Issue by doditaly** [troglobit/watchdogd#6]
In the supervisor struct, label size is not enough for file names greater of 16 chars. I think it could be chenged to 48.

```
static struct supervisor {
	int   id;		/* 0-255, -1: Free */
	pid_t pid;
	char  label[48];	/* Process name, or label. */
	int   timeout;		/* Period time, in msec. */
	uev_t watcher;		/* Process timer */
	int   ack;		/* Next expected ACK from process */
} process[256];                 /* Max ID 0-255 */
```

**Comment by troglobit** [comment]
The label is not for file names, but a operator set system-specific unique name.  File names in POSIX can be up to 255 chars so even 48 would probably be too small for some users.

**Comment by doditaly** [comment]
Days ago I've created a program named watchdogd_example, to make some tests with the apis, and I noticed that the name in the watchdogd.state file (label) was been chopped, so I've suggested to increase the label size.
48 is because the wtd_t struct has label size of 48.

**Comment by troglobit** [comment]
OK, that's fair, honestly didn't even thing about `wdog_reason_t`.
