### ISSUE TITLE
supervison script

### ISSUE THREAD

**Issue by doditaly** [troglobit/watchdogd#7]
Why supervisor has't the user script? It sould be very usefull.

**Comment by doditaly** [comment]
It could have script and "global" script (the same used by the monitor plugins).

**Comment by troglobit** [comment]
It's just not implemented, I did not have use for it myself.  If you send a pull-request with a proposal we can talk about it.

**Comment by doditaly** [comment]
ok.
I have done "git clone", create new branch, make changes, commit and push, but the following error occurred:

```
remote: Permission to troglobit/watchdogd.git denied to doditaly.
fatal: unable to access 'https://github.com/troglobit/watchdogd/': The requested URL returned error: 403
```

**Comment by troglobit** [comment]
GitHub repositorys are not shared. You have to Fork the repository to your own user, do the change in a separate branch, and then submit a pull request.

There's some information here, but you can probably find more help with a little bit of googling. The process is usually the exact same for all GitHub projects.

https://help.github.com/articles/creating-a-pull-request/
